### ISSUE TITLE
IGoNaNoGenMo

### ISSUE THREAD

**Issue by willf** [dariusk/NaNoGenMo#14]
Count me in, dariousk.

Next year: NaNoGenMo challenge generator.

**Comment by dariusk** [comment]
Hooray, you're here!

**Comment by willf** [comment]
Ok, my very first version is up at https://github.com/willf/NaNoGenMo

100k words at: https://github.com/willf/NaNoGenMo/blob/master/novels/1984-version-1.txt

**Comment by dariusk** [comment]
So I'm guessing you're doing some kind of find-replace on word types? Swapping adjectives for other adjectives, etc?

**Comment by dariusk** [comment]
Also, a curious preponderance of the word "bear".

![hmm](http://tinysubversions.com/pics/333fba1a448687e6519b8c96527ba25e.png)

**Comment by willf** [comment]
Yes, right on both counts.

On Thu, Nov 7, 2013 at 9:25 AM, dariusk notifications@github.com wrote:

> Also, a curious preponderance of the word "bear".
> 
> [image: hmm]https://github-camo.global.ssl.fastly.net/50b299836fb0d64139e7f6413f26fedd024947f6/687474703a2f2f74696e7973756276657273696f6e732e636f6d2f706963732f33333366626131613434383638376536353139623863393635323762613235652e706e67
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dariusk/NaNoGenMo/issues/14#issuecomment-27968390
> .

## 

Will

**Comment by willf** [comment]
Final version: https://github.com/willf/NaNoGenMo/blob/master/novels/1984-version-3.md

**Comment by dariusk** [comment]
Better late than never! (Also, great job.)

**Comment by willf** [comment]
Heh. I did finish quite a while ago, but never pressed the 'closed' button.

On Fri, Aug 22, 2014 at 11:55 AM, Darius Kazemi notifications@github.com
wrote:

> Better late than never! (Also, great job.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dariusk/NaNoGenMo/issues/14#issuecomment-53078759.

## 

Will
