### ISSUE TITLE
visibleCode Novel Generator

### ISSUE THREAD

**Issue by SChandler** [dariusk/NaNoGenMo#84]
This effort at coded generation of a 50,000 word novel will use will use some basic structured content at the chapter level, with an input FORM for each chapter [not sure if this will be identical or follow a structured story development "Pattern" with variable selectors/components. This content will be combined with unstructured, and random components for creating a relatively short and unique novel.

**Comment by hugovk** [comment]
@SChandler This is the 2013 NaNoGenMo repo.

Would you like to open your issue on the 2014 repo?

https://github.com/dariusk/NaNoGenMo-2014/

**Comment by SChandler** [comment]
Thanks Hugo!
