### ISSUE TITLE
Googly Vogonicus

### ISSUE THREAD

**Issue by edsu** [dariusk/NaNoGenMo#85]
On @hugovk's suggestion I'm going to try to generate a 50,000 word version of [Vogon Poetry](http://inkdroid.org/vogon) derived from Google's auto-complete. It'll be horrific, and possibly repetitive ... but hopefully it will be VOGONIC!

**Comment by edsu** [comment]
Work progressing at https://github.com/edsu/googly_vogonicus.

**Comment by edsu** [comment]
I just realized this isn't reallly a novel per-se. Does an epic poem of 50,000 words fit with NaNoGenMo?

**Comment by hugovk** [comment]
Sure, why not? [The rules](https://github.com/dariusk/NaNoGenMo#the-rules) say:

> The "novel" is defined however you want. It could be 50,000 repetitions of the word "meow". It could literally grab a random novel from Project Gutenberg. It doesn't matter, as long as it's 50k+ words.

By the way, this is the 2013 repo. The [2014 repo is here](https://github.com/dariusk/NaNoGenMo-2014).

**Comment by edsu** [comment]
D'oh! Moved to [#71](https://github.com/dariusk/NaNoGenMo-2014/issues/71).
