### ISSUE TITLE
Anyone want to participate in a Nanogenmo One Off Podcast Event?

### ISSUE THREAD

**Issue by VincentToups** [dariusk/NaNoGenMo#89]
I'm thinking about organizing one.  Is there any interest?

**Comment by VincentToups** [comment]
I suppose a bunch of us could get on Skype and have a loosely structured discussion of our attempts this year and what they might mean?

**Comment by MichaelPaulukonis** [comment]
Flap our tongues on our lips instead of our fingers on our keyboards?

**Comment by enkiv2** [comment]
I might be able to participate, depending upon when it occurs.

**Comment by VincentToups** [comment]
@enkiv2 we can make it whenever.  There seem to just be three of us.  What dates would work for you?

**Comment by enkiv2** [comment]
Maybe this saturday? I'm off on thursday and friday, but that's just
because I'm in the US.

**Comment by MichaelPaulukonis** [comment]
Saturday. Or possibly Friday (US as well, and a house full of in-laws).

**Comment by VincentToups** [comment]
How does everyone feel about  4pm EST Saturday?

**Comment by enkiv2** [comment]
I have another meeting on skype at 2pm EST, but it _should_ be finished by
4pm. If not, I suppose I can join a little late. So, it sounds good to me.

**Comment by hugovk** [comment]
By the way, you might get more participants if you post this in the [2014 repo](https://github.com/dariusk/NaNoGenMo-2014) instead of this, the 2013 repo...

**Comment by VincentToups** [comment]
Oops!

**Comment by VincentToups** [comment]
[Thread in the 2014 repo](https://github.com/dariusk/NaNoGenMo-2014/issues/119)
